on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
        - windows-2019
        - windows-2016
        - ubuntu-20.04
        - ubuntu-18.04
        # - macos-11.0
        - macos-10.15
        php:
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - 7.3
        - 7.4
        - 8.0
        exclude:
        - operating-system: windows-2019
          php: 5.6
        - operating-system: windows-2016
          php: 5.6
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      # Dependency patches for PHP5.6.
      - run: rm composer.lock
        if: ${{ matrix.php == '5.6' }}
      - run: composer.phar --dev vimeo/psalm phpunit/phpunit
        if: ${{ matrix.php == '5.6' }}
      - run: composer require --dev phpunit/phpunit:^5.0.0
        if: ${{ matrix.php == '5.6' }}

      # Dependency patches for PHP7.0.
      - run: rm composer.lock
        if: ${{ matrix.php == '7.0' }}
      - run: composer.phar --dev vimeo/psalm phpunit/phpunit
        if: ${{ matrix.php == '7.0' }}
      - run: composer require --dev phpunit/phpunit:^6.5.0
        if: ${{ matrix.php == '7.0' }}

      # Dependency patches for PHP7.1.
      - run: rm composer.lock
        if: ${{ matrix.php == '7.1' }}
      - run: composer require --dev phpunit/phpunit:^7.5.0
        if: ${{ matrix.php == '7.1' }}

      # Dependency patches for PHP7.2.
      - run: rm composer.lock
        if: ${{ matrix.php == '7.2' }}
      - run: composer require --dev phpunit/phpunit:^8.5.0
        if: ${{ matrix.php == '7.2' }}

      - run: composer install
      - run: test -f vendor/bin/psalm && vendor/bin/psalm
      - run: mkdir -p test_results
      - run: vendor/bin/phpunit --whitelist src --coverage-text tests/ | tee test_results/unit
      - run: grep -E "^\s*Lines:\s*100\.00%\s*\([0-9]+\/[0-9]+\)\s*$" test_results/unit
        shell: bash
